// Generated from crates/contracts/src/lib.rs by tools/contracts/generate-typescript.mjs.
// Regenerate with `pnpm generate:contracts`; do not edit this file manually.
// Public contracts contain opaque identifiers and scoped URLs, never filesystem paths.

export type MediaSessionId = string;

export type StreamId = string;

export type SubtitleSourceId = string;

export type CueId = string;

export type TokenId = string;

export type DictionaryEntryId = string;

export type DraftId = string;

export type JobId = string;

export type TimestampUs = number;

export interface DimensionsV1 {
  width: number;
  height: number;
}

export type MediaStreamKindV1 = 'video' | 'audio' | 'subtitle';

export type SubtitleKindV1 = 'text' | 'image';

export interface MediaStreamV1 {
  stream_id: StreamId;
  index: number;
  kind: MediaStreamKindV1;
  codec: string;
  codec_profile: string | null;
  language: string | null;
  title: string | null;
  is_default: boolean;
  is_forced: boolean;
  channels: number | null;
  sample_rate: number | null;
  width: number | null;
  height: number | null;
  pixel_format: string | null;
  frame_rate: number | null;
  subtitle_kind: SubtitleKindV1 | null;
}

export type PlaybackPlanKindV1 =
  'direct' | 'remux' | 'convert_audio' | 'transcode_video' | 'unsupported';

export type JobStateV1 =
  'probing' | 'awaiting_approval' | 'queued' | 'running' | 'ready' | 'failed' | 'cancelled';

export type EstimatedCostV1 = 'negligible' | 'low' | 'high';

export interface PlaybackTimelineMapV1 {
  source_origin_us: TimestampUs;
  playback_origin_us: TimestampUs;
  source_offset_us: TimestampUs;
  source_duration_us: TimestampUs;
  playback_duration_us: TimestampUs;
}

export interface PlaybackPlanV1 {
  kind: PlaybackPlanKindV1;
  state: JobStateV1;
  source_stream_ids: StreamId[];
  output_container: string | null;
  output_codecs: string[];
  timeline_map: PlaybackTimelineMapV1;
  estimated_cost: EstimatedCostV1;
  cache_key: string | null;
  progress: number | null;
  reason_codes: string[];
}

export type SourceScopePersistenceV1 = 'session' | 'user_approved_persistent';

export interface MediaSessionV1 {
  session_id: MediaSessionId;
  display_name: string;
  source_fingerprint: string;
  duration_us: TimestampUs;
  dimensions: DimensionsV1 | null;
  container: string;
  video_streams: MediaStreamV1[];
  audio_streams: MediaStreamV1[];
  subtitle_streams: MediaStreamV1[];
  selected_video_stream_id: StreamId | null;
  selected_audio_stream_id: StreamId | null;
  playback_plan: PlaybackPlanV1;
  playback_url: string;
  source_scope_persistence: SourceScopePersistenceV1;
  warnings: string[];
}

export type PlaybackStateV1 = 'loading' | 'playing' | 'paused' | 'seeking' | 'ended' | 'error';

export interface PlaybackCheckpointV1 {
  session_id: MediaSessionId;
  revision: number;
  state: PlaybackStateV1;
  position_us: TimestampUs;
  playback_rate_milli: number;
  selected_audio_stream_id: StreamId | null;
  observed_monotonic_us: number;
}

export interface CapabilityCandidateV1 {
  container: string;
  video_codec: string | null;
  audio_codec: string | null;
  can_play: string;
  media_capabilities_supported: boolean | null;
  media_capabilities_smooth: boolean | null;
}

export interface PlaybackCapabilityReportV1 {
  revision: number;
  candidates: CapabilityCandidateV1[];
  tested_webview: string;
}

export type DecodeTestOutcomeV1 = 'not_tested' | 'first_frame_presented' | 'failed';

export type SubtitleOriginV1 = 'adjacent_file' | 'selected_file' | 'embedded_text_track';

export type SubtitleFormatV1 = 'srt' | 'ass' | 'ssa' | 'vtt';

export interface SubtitleSourceV1 {
  subtitle_source_id: SubtitleSourceId;
  origin: SubtitleOriginV1;
  display_name: string;
  format: SubtitleFormatV1;
  language: string | null;
  source_version: string;
  embedded_stream_id: StreamId | null;
}

export interface SubtitleStyleHintV1 {
  alignment: number | null;
  actor: string | null;
}

export interface SubtitleCueV1 {
  cue_id: CueId;
  start_us: TimestampUs;
  end_us: TimestampUs;
  plain_text: string;
  source_text: string;
  track_order: number;
  style_hint: SubtitleStyleHintV1;
}

export interface TokenV1 {
  token_id: TokenId;
  surface: string;
  byte_start: number;
  byte_end: number;
  lemma: string;
  reading: string;
  pronunciation: string | null;
  part_of_speech: string[];
  lookup_candidate: boolean;
}

export interface DictionarySenseV1 {
  glosses: string[];
  parts_of_speech: string[];
  restrictions: string[];
  fields: string[];
  dialects: string[];
  misc: string[];
}

export type PitchLevelV1 = 'low' | 'high';

export interface PitchAccentV1 {
  reading: string;
  morae: string[];
  levels: PitchLevelV1[];
  drop_after_mora: number | null;
  source: string;
}

export interface DictionaryEntrySummaryV1 {
  entry_id: DictionaryEntryId;
  headwords: string[];
  readings: string[];
  senses: DictionarySenseV1[];
  pitch_accents: PitchAccentV1[];
  jlpt_level: number | null;
  jlpt_source: string | null;
  match_reason: string;
  priority_score: number;
}

export interface AnalyzedTokenV1 {
  token: TokenV1;
  dictionary: DictionaryEntrySummaryV1[];
}

export interface AnalyzedCueV1 {
  cue: SubtitleCueV1;
  tokens: AnalyzedTokenV1[];
}

export type AnalysisStateV1 = 'pending' | 'partial' | 'complete' | 'failed';

export interface SubtitleWindowV1 {
  window_id: string;
  revision: number;
  session_id: MediaSessionId;
  subtitle_source_id: SubtitleSourceId;
  window_start_us: TimestampUs;
  window_end_us: TimestampUs;
  cues: AnalyzedCueV1[];
  recommended_refresh_at_us: TimestampUs;
  analysis_state: AnalysisStateV1;
  warnings: string[];
}

export interface TranslationWindowV1 {
  window_id: string;
  revision: number;
  session_id: MediaSessionId;
  subtitle_source_id: SubtitleSourceId;
  window_start_us: TimestampUs;
  window_end_us: TimestampUs;
  cues: SubtitleCueV1[];
  recommended_refresh_at_us: TimestampUs;
  warnings: string[];
}

export interface CardDraftV1 {
  draft_id: DraftId;
  revision: number;
  session_id: MediaSessionId;
  subtitle_source_id: SubtitleSourceId;
  subtitle_source_version: string;
  cue: SubtitleCueV1;
  token: TokenV1;
  dictionary_entry: DictionaryEntrySummaryV1 | null;
  observed_source_time_us: TimestampUs;
  source_fingerprint: string;
}

export interface CreateCardRequestV1 {
  draft_id: DraftId;
  expected_draft_revision: number;
  profile_id: string;
  editable_fields: Record<string, string>;
  confirmed: boolean;
}

export type CreateCardOutcomeV1 =
  'created' | 'already_exists' | 'failed_retryable' | 'failed_terminal';

export interface CreateCardResultV1 {
  job_id: JobId;
  note_id: number | null;
  media_names: string[];
  outcome: CreateCardOutcomeV1;
}

export interface AppErrorV1 {
  code: string;
  message: string;
  retryable: boolean;
  diagnostics: string | null;
}

export interface DependencyHealthV1 {
  component: string;
  available: boolean;
  version: string | null;
  action: string | null;
  error: AppErrorV1 | null;
}

export interface AppHealthV1 {
  checks: DependencyHealthV1[];
}

export interface CardProfileSettingsV1 {
  profile_id: string;
  deck_name: string;
  model_name: string;
  field_mapping: Record<string, string>;
  tags: string[];
}

export interface UserSettingsV1 {
  preferred_audio_languages: string[];
  playback_cache_max_bytes: number;
  playback_cache_max_age_days: number;
  clip_leading_padding_us: TimestampUs;
  clip_trailing_padding_us: TimestampUs;
  anki_port: number;
  anki_timeout_ms: number;
  card_profile: CardProfileSettingsV1;
}

export interface ToolSelectionResultV1 {
  component: string;
  configured: boolean;
  restart_required: boolean;
}

export interface SubtitleCandidateV1 {
  candidate_id: string;
  display_name: string;
  format: SubtitleFormatV1;
  language: string | null;
}

export interface SubtitleDiscoveryV1 {
  candidates: SubtitleCandidateV1[];
  recommended_candidate_id: string | null;
}

export interface RecentMediaV1 {
  source_fingerprint: string;
  display_name: string;
}
